USE NotesDB;

-- Create Tables
CREATE TABLE note (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    description TEXT
);

-- Add Dummy Data
INSERT INTO `note` (`title`,`description`) VALUES ("ultricies adipiscing, enim mi","sit amet ornare lectus justo eu arcu. Morbi"),("vitae dolor. Donec fringilla. Donec","pharetra, felis eget varius ultrices, mauris ipsum"),("urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas","sit amet, faucibus ut, nulla. Cras eu tellus"),("Nunc mauris sapien, cursus in, hendrerit consectetuer,","massa. Vestibulum accumsan neque et nunc. Quisque"),("eu, ligula. Aenean euismod mauris","natoque penatibus et magnis dis"),("dictum magna. Ut tincidunt orci quis lectus.","est, congue a, aliquet vel, vulputate eu, odio. Phasellus"),("Cras eget nisi dictum augue malesuada malesuada.","eros. Proin ultrices. Duis volutpat"),("diam.","quis, tristique ac, eleifend vitae, erat. Vivamus nisi."),("eu metus. In lorem. Donec elementum, lorem ut aliquam","libero. Donec consectetuer mauris id sapien. Cras dolor"),("dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit,","quis accumsan convallis, ante lectus");
INSERT INTO `note` (`title`,`description`) VALUES ("odio a purus. Duis elementum, dui quis","montes, nascetur ridiculus mus. Donec dignissim magna a tortor."),("Quisque tincidunt pede ac urna. Ut tincidunt","ante dictum mi, ac mattis velit justo nec ante."),("mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.","mi eleifend egestas. Sed pharetra,"),("urna et arcu imperdiet ullamcorper. Duis","Nulla eget metus eu erat semper rutrum."),("Cras sed leo. Cras vehicula aliquet libero. Integer in magna.","Quisque porttitor eros nec tellus. Nunc lectus pede,"),("orci, adipiscing non, luctus sit amet,","cursus et, magna. Praesent interdum"),("mollis lectus pede","Duis a mi fringilla mi lacinia mattis."),("Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique","semper erat, in consectetuer ipsum"),("Proin sed turpis nec mauris blandit mattis. Cras eget nisi","non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc"),("magna. Duis dignissim tempor arcu. Vestibulum ut eros non","Etiam vestibulum massa rutrum magna.");
INSERT INTO `note` (`title`,`description`) VALUES ("purus. Maecenas libero est, congue a, aliquet vel, vulputate","hendrerit consectetuer, cursus et, magna."),("lorem","rhoncus. Proin nisl sem, consequat"),("eros. Proin ultrices. Duis volutpat nunc sit amet metus.","faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse"),("senectus et","lectus quis massa. Mauris vestibulum,"),("malesuada id, erat.","leo. Vivamus nibh dolor, nonummy ac, feugiat"),("risus. Morbi metus. Vivamus euismod","parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor."),("posuere","non, bibendum sed, est. Nunc"),("ut ipsum ac mi eleifend","erat nonummy ultricies ornare, elit elit fermentum risus,"),("dictum. Phasellus","id, erat. Etiam vestibulum massa rutrum"),("et, magna. Praesent","quis arcu vel quam dignissim");
INSERT INTO `note` (`title`,`description`) VALUES ("euismod urna. Nullam lobortis quam a felis ullamcorper","vehicula. Pellentesque tincidunt tempus risus."),("Nulla facilisis. Suspendisse commodo","vitae risus. Duis a mi fringilla mi lacinia mattis. Integer"),("non enim. Mauris quis turpis","ligula consectetuer rhoncus. Nullam velit dui, semper"),("parturient montes,","risus varius orci, in consequat enim diam vel arcu. Curabitur"),("Cum sociis natoque penatibus et magnis dis parturient","vestibulum. Mauris magna. Duis dignissim tempor"),("scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed","et risus. Quisque libero lacus, varius et, euismod"),("justo. Praesent","dictum eu, placerat eget, venenatis a,"),("eu","mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus."),("Nunc sollicitudin commodo","vel est tempor bibendum. Donec felis orci, adipiscing non, luctus"),("nunc risus varius","pede, ultrices a, auctor non,");
INSERT INTO `note` (`title`,`description`) VALUES ("eu, eleifend nec, malesuada ut, sem. Nulla interdum.","ad litora torquent per conubia nostra, per inceptos"),("Cum sociis natoque penatibus et","et, lacinia vitae, sodales at,"),("a, magna. Lorem ipsum dolor sit","faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus."),("convallis dolor. Quisque tincidunt","Cras convallis convallis dolor. Quisque tincidunt pede ac urna."),("pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac","dolor. Fusce mi lorem, vehicula et,"),("quis accumsan convallis, ante","orci, adipiscing non, luctus sit amet, faucibus"),("molestie. Sed id risus quis diam luctus lobortis.","lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy"),("Nullam scelerisque neque sed","consequat purus. Maecenas libero est,"),("Nulla eget metus eu","imperdiet nec, leo. Morbi neque tellus, imperdiet non,"),("ante blandit viverra. Donec","at risus. Nunc ac sem ut dolor");
INSERT INTO `note` (`title`,`description`) VALUES ("eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet","Aliquam tincidunt, nunc ac mattis ornare,"),("Cum sociis","quis, pede. Praesent eu dui. Cum sociis natoque"),("consequat nec, mollis vitae, posuere","lacus vestibulum lorem, sit amet ultricies sem magna nec"),("sociosqu ad litora","porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc"),("mattis. Cras eget","odio. Aliquam vulputate ullamcorper magna."),("neque. Morbi quis urna. Nunc quis arcu","interdum. Nunc sollicitudin commodo ipsum."),("Vestibulum ante ipsum primis in faucibus orci luctus et","Proin vel nisl. Quisque fringilla euismod enim. Etiam"),("semper auctor. Mauris","felis ullamcorper viverra. Maecenas iaculis aliquet"),("mollis. Duis sit amet diam","nisi nibh lacinia orci, consectetuer euismod est arcu ac orci."),("sit amet ornare lectus justo eu","arcu et pede. Nunc sed orci lobortis");
INSERT INTO `note` (`title`,`description`) VALUES ("eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec","et arcu imperdiet ullamcorper. Duis at lacus. Quisque"),("erat. Etiam vestibulum","sociis natoque penatibus et magnis dis parturient montes, nascetur"),("Ut","vitae erat vel pede blandit congue. In scelerisque"),("Pellentesque habitant","amet lorem semper auctor. Mauris vel turpis."),("ullamcorper, nisl","molestie dapibus ligula. Aliquam erat volutpat. Nulla"),("et magnis dis parturient montes, nascetur ridiculus mus.","dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu"),("Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui,","erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt"),("gravida","feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem"),("dolor egestas rhoncus. Proin nisl","felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem,"),("risus varius","semper rutrum. Fusce dolor quam, elementum at,");
INSERT INTO `note` (`title`,`description`) VALUES ("gravida nunc sed pede. Cum","pede. Praesent eu dui. Cum"),("metus vitae velit egestas","Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut"),("ante lectus convallis est, vitae","imperdiet ullamcorper. Duis at lacus. Quisque purus sapien,"),("non, egestas","bibendum. Donec felis orci, adipiscing non, luctus"),("nascetur ridiculus mus.","vitae erat vel pede blandit"),("dolor sit amet, consectetuer adipiscing elit. Etiam laoreet,","luctus lobortis. Class aptent taciti sociosqu ad"),("Sed dictum. Proin eget odio. Aliquam vulputate","porttitor interdum. Sed auctor odio a purus. Duis elementum, dui"),("arcu vel quam dignissim","ipsum nunc id enim. Curabitur massa. Vestibulum"),("justo sit amet nulla. Donec non justo. Proin non massa","Sed dictum. Proin eget odio."),("nibh vulputate mauris sagittis placerat. Cras","odio. Aliquam vulputate ullamcorper magna. Sed");
INSERT INTO `note` (`title`,`description`) VALUES ("Duis a mi fringilla","commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur"),("nec, imperdiet nec, leo.","in molestie tortor nibh sit amet"),("ipsum dolor","Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec,"),("ut, pellentesque eget, dictum","feugiat. Lorem ipsum dolor sit amet, consectetuer"),("Donec felis orci, adipiscing non, luctus sit amet, faucibus","imperdiet nec, leo. Morbi neque tellus,"),("augue","eu turpis. Nulla aliquet. Proin"),("cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam","ac turpis egestas. Fusce aliquet magna a neque."),("elit fermentum risus, at fringilla","vestibulum massa rutrum magna. Cras convallis"),("quis, pede. Suspendisse dui. Fusce diam","mauris elit, dictum eu, eleifend"),("Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet.","aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus");
INSERT INTO `note` (`title`,`description`) VALUES ("parturient montes, nascetur ridiculus","sodales purus, in molestie tortor nibh sit"),("aliquam eros turpis non","ut mi. Duis risus odio,"),("eget","turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut"),("primis in faucibus orci","eget, dictum placerat, augue. Sed molestie. Sed id risus quis"),("ut aliquam iaculis, lacus pede sagittis augue, eu","non, vestibulum nec, euismod in,"),("fermentum metus. Aenean sed pede nec ante","In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas."),("viverra. Donec tempus, lorem fringilla","lorem, eget mollis lectus pede et risus. Quisque libero lacus,"),("non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec","dolor. Fusce mi lorem, vehicula et, rutrum"),("aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare","ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum"),("diam. Pellentesque habitant morbi tristique","nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus.");
